#!/bin/bash

if hash docker 2>/dev/null; then
for ((i=1;i<=$#;i++));
do

THUNDERHUB_ID=$(echo $(docker ps | awk '/docker_thunderhub/'|awk ' {print $1}' | awk 'NR==1'))
export THUNDERHUB_ID
THUNDERHUB_IMAGE=$(echo $(docker images | awk '/docker_thunderhub/'|awk ' {print $3}' | awk 'NR==1'))
export THUNDERHUB_IMAGE

RTL_ID=$(echo $(docker ps | awk '/rtl/'|awk ' {print $1}' | awk 'NR==1'))
export RTL_ID
RTL_IMAGE=$(echo $(docker images | awk '/rtl/'|awk ' {print $3}' | awk 'NR==1'))
export RTL_IMAGE

LND_ID=$(echo $(docker ps | awk '/docker_lnd/'|awk ' {print $1}' | awk 'NR==1'))
export LND_ID
LND_IMAGE=$(echo $(docker images | awk '/docker_lnd/'|awk ' {print $3}' | awk 'NR==1'))
export LND_IMAGE

LNDG_ID=$(echo $(docker ps | awk '/cryptosharks131/'|awk ' {print $1}' | awk 'NR==1'))
export LNDG_ID
LNDG_IMAGE=$(echo $(docker images | awk '/cryptosharks131/'|awk ' {print $3}' | awk 'NR==1'))
export LNDG_IMAGE

DOCS_ID=$(echo $(docker ps | awk '/docker_docs/'|awk ' {print $1}' | awk 'NR==1'))
export DOCS_ID
DOCS_IMAGE=$(echo $(docker images | awk '/docker_docs/'|awk ' {print $3}' | awk 'NR==1'))
export DOCS_IMAGE

BITCOIND_ID=$(echo $(docker ps | awk '/docker_bitcoind/'|awk ' {print $1}' | awk 'NR==1'))
export BITCOIND_ID
BITCOIND_IMAGE=$(echo $(docker images | awk '/docker_bitcoind/'|awk ' {print $3}' | awk 'NR==1'))
export BITCOIND_IMAGE

TOR_ID=$(echo $(docker ps | awk '/docker_tor/'|awk ' {print $1}' | awk 'NR==1'))
export TOR_ID
TOR_IMAGE=$(echo $(docker images | awk '/docker_tor/'|awk ' {print $3}' | awk 'NR==1'))
export TOR_IMAGE

BTCD_ID=$(echo $(docker ps | awk '/btcd/'|awk ' {print $1}' | awk 'NR==1'))
export BTCD_ID
BTCD_IMAGE=$(echo $(docker images | awk '/btcd/'|awk ' {print $3}' | awk 'NR==1'))
export BTCD_IMAGE

    if [[ ${!i} = info ]]; then
        ((i++))
        play ids
        echo
        echo "ARGS:"
        echo
        echo "!i = ${!i}"
        echo "0 = ${0}" #/usr/local/bin/play
        echo "1 = ${1}"
        echo "2 = ${2}"
        echo "3 = ${3}"
        echo "4 = ${4}"
        echo "5 = ${5}"
        echo "6 = ${6}"
        echo "7 = ${7}"
        exit

    elif [[ ${!i} = *ids ]]; then
        ((i++))
        echo
        echo "THUNDERHUB_ID:            $THUNDERHUB_ID"
        echo "RTL_ID:                   $RTL_ID"
        echo "LND_ID:                   $LND_ID"
        echo "LNDG_ID:                  $LNDG_ID"
        echo "DOCS_ID:                  $DOCS_ID"
        echo "BITCOIND_ID:              $BITCOIND_ID"
        echo "TOR_ID:                   $TOR_ID"
        echo
        #[ -z "$BTCD_ID" ] && echo "try 'make btcd'"|| echo BTCD_ID:
        #[ -z "$BTCD_ID" ] && echo || echo $BTCD_ID
        exit

    elif [[ ${!i} = *images ]]; then
        ((i++))
        echo "THUNDERHUB_IMAGE:          $THUNDERHUB_IMAGE"
        echo "RTL_IMAGE:                 $RTL_IMAGE"
        echo "LND_IMAGE:                 $LND_IMAGE"
        echo "LNDG_IMAGE:                $LNDG_IMAGE"
        echo "DOCS_IMAGE:                $DOCS_IMAGE"
        echo "BITCOIND_IMAGES:           $BITCOIND_IMAGE"
        echo "TOR_IMAGE:                 $TOR_IMAGE"
        #[ -z "$BTCD_IMAGE" ] && echo "try 'make btcd'"|| echo BTCD_IMAGE:
        #[ -z "$BTCD_IMAGE" ] && echo || echo $BTCD_IMAGE
        exit

    elif [[ ${!i} = lnd ]]; then
        #access play-lnd
        #NOTE: $0 /usr/local/bin/play
        #      $1 lnd
        ((i++))
        play-lnd $2 $3 $4 $5 $6 $7
        exit

    elif [[ ${!i} = shell ]]; then
        ((i++))
        play-lnd shell
        exit

    elif [[ ${!i} = newaddress ]]; then
        ((i++))
        play-lnd newaddress
        exit

    elif [[ ${!i} = start ]]; then
        ((i++))
        echo LND_ID = $LND_ID
        [[ -z $LND_ID ]]   && echo NOT EXIST $LND_ID && docker-compose up lnd &
        [[ ! -z  $LND_ID ]] && echo NOT $LND_ID
        [[ ! -z "$LND_ID" ]] && echo QUOTE NOT $LND_ID
        play-lnd start &
        exit

    elif [[ ${!i} = restart ]]; then
        ((i++))
        echo LND_ID = $LND_ID
        [[ -z $LND_ID ]]   && echo NOT EXIST $LND_ID && docker-compose up lnd &
        [[ ! -z  $LND_ID ]] && echo NOT $LND_ID
        [[ ! -z "$LND_ID" ]] && echo QUOTE NOT $LND_ID
        play-lnd restart &
        exit

    elif [[ ${!i} = stop ]]; then
        ((i++))
        play-lnd stop $LND_ID
        exit

    elif [[ ${!i} = bitcoin* ]]; then
        ((i++))
        play-bitcoin ${!i} $3 $4 $5 $6 $7
        exit

    elif [[ ${!i} == *help ]]; then
        ((i++))
        echo
        echo "	play                     ids"
        echo "	play                     top"
        echo "	play                     shell"
        echo "	play                     start"
        echo "	play                     stop"
        echo "	play                     iftop"
        echo "	play                     ifconfig"
        echo "	play                     newaddress"
        echo "	play                     total-balance"
        echo "	play                     confirmed-balance"
        echo "	play                     unconfirmed-balance"
        echo "	play                     lncli -n signet walletbalance"
        echo
        echo "	play                     tor-iftop"
        echo
        echo "	Examples:"
        echo
        echo "	play bitcoin id"
        echo "	play bitcoin iftop"
        echo "	play bitcoin netinfo 5"
        echo "	play bitcoin gettxoutsetinfo"
        echo "	play bitcoin getmininginfo"
        echo
        echo "	play bitcoin '<COMMAND>'"
        echo "	play bitcoin 'bitcoin-cli getblockhash 1000'"
        echo "	play bitcoin 'bitcoin-cli getblock \$(bitcoin-cli getblockhash 0)'"
        echo
        echo "	play lnd"
        echo "	play lnd id"
        echo "	play lnd top"
        echo "	play lnd info"
        echo "	play lnd ifconfig"
        echo "	play lnd newaddress"
        echo "	play lnd total-balance"
        echo "	play lnd '<COMMAND>'"
        echo
        echo "	play-lnd balance"
        exit

    elif [[ ${!i} == *shell ]]; then
        ((i++))
        docker exec -it $LND_ID /bin/bash
        exit

    elif [[ ${!i} == iftop ]]; then
        ((i++))
        docker exec -it $LND_ID /bin/bash -c "test -x '$(which iftop)' && iftop -P -p -i eth0 $2 $3 $4 $5 || apk add iftop && iftop -P -p -i eth0 $2 $3 $4 $5"
        exit

    elif [[ ${!i} == tor-iftop ]]; then
        ((i++))
        docker exec -it $TOR_ID sh -c "test -x '$(which iftop)' && iftop -P -p -i eth0 $2 $3 $4 $5 || apk add iftop && iftop -P -p -i eth0 $2 $3 $4 $5"
        exit

    elif [[ ${!i} = total-balance ]]; then
        ((i++))
        docker exec $LND_ID sh -c "lncli -n signet walletbalance | jq -r .total_balance"
        exit
    elif [[ ${!i} = confirmed-balance ]]; then
        ((i++))
        docker exec $LND_ID sh -c "lncli -n signet walletbalance | jq -r .confirmed_balance"
        exit
    elif [[ ${!i} = unconfirmed-balance ]]; then
        ((i++))
        docker exec $LND_ID sh -c "lncli -n signet walletbalance | jq -r .unconfirmed_balance"
        exit

    elif [[ -n ${!i} ]]; then
        ((i++))
        docker exec $LND_ID /bin/bash -c "$1 $2 $3 $4 $5 $6"
        exit
    fi

done;
#play     ids;
play     help;
fi #end if docker hash

