#!/bin/bash

if hash docker 2>/dev/null; then

THUNDERHUB_ID=$(echo $(docker ps | awk '/thunderhub/'|awk ' {print $1}' | awk 'NR==1'))
export THUNDERHUB_ID
THUNDERHUB_IMAGE=$(echo $(docker images | awk '/thunderhub/'|awk ' {print $3}' | awk 'NR==1'))
export THUNDERHUB_IMAGE

RTL_ID=$(echo $(docker ps | awk '/rtl/'|awk ' {print $1}' | awk 'NR==1'))
export RTL_ID
RTL_IMAGE=$(echo $(docker images | awk '/rtl/'|awk ' {print $3}' | awk 'NR==1'))
export RTL_IMAGE

LND_ID=$(echo $(docker ps | awk '/lnd/'|awk ' {print $1}' | awk 'NR==1'))
export LND_ID
LND_IMAGE=$(echo $(docker images | awk '/lnd/'|awk ' {print $3}' | awk 'NR==1'))
export LND_IMAGE

DOCS_ID=$(echo $(docker ps | awk '/docs/'|awk ' {print $1}' | awk 'NR==1'))
export DOCS_ID
DOCS_IMAGE=$(echo $(docker images | awk '/docs/'|awk ' {print $3}' | awk 'NR==1'))
export DOCS_IMAGE

BITCOIND_ID=$(echo $(docker ps | awk '/bitcoind/'|awk ' {print $1}' | awk 'NR==1'))
export BITCOIND_ID
BITCOIND_IMAGE=$(echo $(docker images | awk '/bitcoind/'|awk ' {print $3}' | awk 'NR==1'))
export BITCOIND_IMAGE

TOR_ID=$(echo $(docker ps | awk '/tor/'|awk ' {print $1}' | awk 'NR==1'))
export TOR_ID
TOR_IMAGE=$(echo $(docker images | awk '/tor/'|awk ' {print $3}' | awk 'NR==1'))
export TOR_IMAGE

for ((i=1;i<=$#;i++));
do

    if [[ ${!i} = *ids ]]; then
        ((i++))
        echo THUNDERHUB_ID:
        echo $THUNDERHUB_ID
        echo RTL_ID:
        echo $RTL_ID
        echo LND_ID:
        echo $LND_ID
        echo DOCS_ID:
        echo $DOCS_ID
        echo BITCOIND_ID:
        echo $BITCOIND_ID
        echo TOR_ID:
        echo $TOR_ID
        exit

    elif [[ ${!i} = *images ]]; then
        ((i++))
        echo THUNDERHUB_IMAGE:
        echo $THUNDERHUB_IMAGE
        echo RTL_IMAGE:
        echo $RTL_IMAGE
        echo LND_IMAGE:
        echo $LND_IMAGE
        echo DOCS_IMAGE:
        echo $DOCS_IMAGE
        echo BITCOIND_IMAGES:
        echo $BITCOIND_IMAGE
        echo TOR_IMAGE:
        echo $TOR_IMAGE
        exit

    elif [[ ${!i} = top ]]; then
        ((i++))
        docker top ${!i}
        exit

    elif [[ ${!i} = start ]]; then
        ((i++))
        docker start ${!i}
        exit

    elif [[ ${!i} = stop ]]; then
        ((i++))
        docker stop ${!i}
        exit

    elif [[ ${!i} = *cli ]]; then
        ((i++))
        docker exec -it $BITCOIND_ID sh -c  "/usr/local/bin/bitcoin-cli ${!i}"
        exit

    elif [[ ${!i} = *d ]]; then
        ((i++))
        docker exec -it $BITCOIND_ID sh -c  "/usr/local/bin/bitcoind ${!i}"
        exit

    elif [[ ${!i} = *ep ]]; then
        ((i++))
        docker exec -it $BITCOIND_ID sh -c  "/usr/local/bin/entrypoint &"
        exit

    elif [[ ${!i} = *console ]]; then
        ((i++))
        docker exec -it $BITCOIND_ID bash

    elif [[ ${!i} = *debug ]]; then
        ((i++))
        docker exec -it $BITCOIND_ID sh -c "tail -f /home/root/.bitcoin"

    elif [[ ${!i} == *help ]]; then
        ((i++))
        echo
        echo "play                     ids"
        echo "play                     top <CONTAINER_ID>"
        echo "play                      <command> - execute shell command in container"
        echo "play     -d              '<command>' - send command to bitcoind"
        echo "play     -cli            '<command>' - send command to bitcoin-cli"
        echo
        echo "Examples:"
        echo
        echo "play                     ls"
        echo "play                     cd / & ls -a"
        echo "play                     -cli gettxoutsetinfo"
        echo "play                     -cli getmininginfo"
        echo "play                     -cli 'getblockhash 1000'"
        echo
        echo "docker exec -it $BITCOIND_ID sh -c  '/usr/local/bin/bitcoind -daemon -prune=550'"
        echo "docker exec -it $BITCOIND_ID sh -c  '/usr/local/bin/bitcoin-cli gettxoutsetinfo'"
        echo "docker exec -it $BITCOIND_ID sh -c  '/usr/local/bin/bitcoin-cli getmininginfo'"
        echo "docker exec -it $BITCOIND_ID sh -c  '/usr/local/bin/bitcoin-cli $1'"
        exit

    elif [ -n ${!i} ]; then
        ((i++))
        docker exec -it $BITCOIND_ID sh -c  "$1"
        exit
    fi

done;
play help;
fi #end if docker hash

