#!/bin/bash
#This file is executed when a new block is recieved
#It can be used to automate things in the container
PLAY_BITCOIN_ID=$(play-bitcoin id);
export PLAY_BITCOIN_ID
while [ ! -z "$PLAY_BITCOIN_ID" ]; do
ADDRESS=tb1p2l76fzwaaatk7w567kpkftt5qg9lmvn3uv65c5can63a0z2jqmkqvzlhw7 && \
play-getcoins -a "$(play-getcoins -a $ADDRESS -r true)" > /dev/null 2>&1;
PLAY_BITCOIN_ID=$(play-bitcoin id);
echo $PLAY_BITCOIN_ID
done
